### ISSUE TITLE
[FEATURE] Mobility Extension (RFC0002)

### ISSUE THREAD

**Issue by schlingling** [jvalue/jayvee#123]
## User Story
1. As a {user}
2. I want {to archive GTFS-data from an http-endpoint}
3. So that {this kind of domain specific data gets stored in an SQLite-Database according to the GTFS relational model}

## Notes
A basis for all UACs is the corresponding [RFC0002 Mobility extension](https://github.com/jvalue/jayvee/tree/main/rfc/0002-mobility-extension). The RFC got qualified by multiple iterations, which are listed below. One UACs represents a single requirement, extraced from the final, accepted iteration.
Iterations of [RFC0002 Mobility extension](https://github.com/jvalue/jayvee/tree/main/rfc/0002-mobility-extension):
| **Iteration** | **Scope**                                                                 | **PR** |
|---------------|---------------------------------------------------------------------------|--------|
| 1             | RFC mobility extension using collections: inital concept                  | #111   |
| 2             | FC mobility extension using collections: refinement after feedback-loop   | #115   |
| 3             | RFC mobility extension using file-pickers: change of concept              | #116   |
| 4             | RFC mobility extension using file-pickers: refinement after feedback-loop | #117   |
| 5             | RFC mobility extension using file-pickers: RFC-status ACCEPTED            | #119   |

## User Acceptance Criteria
- [x] [UAC-1] New io-datatype `File` is implemented.  Via #125 and #256
- [x] [UAC-2] New io-datatype `FileSystem` is implemented. Via #126 and #256
- [x] [UAC-3] New io-datatype `None` is implemented. Via #126 
- [x] ~~[UAC-4] The io-datatype `Table` stores the table's name. Obsolet via #164 and #165~~
- [x] ~~[UAC-5] The block LayoutValidator process the new table name coming from Table. Obsolet via #164~~
- [x] ~~[UAC-6] The example.jv-files holds the tables name in Table-Block. Obsolet via #164~~
- [x] [UAC-6.1] The example.jv-files holds the tables name in Loaderblocks. via #166 
- [x] [UAC-7] If a precessor of a block outputs `None`, the execution aborts. via #136 
- [x] [UAC-8] Folderstructure for io-datatypes is introduced. Via #124 and via #126 and via #256
- [x] [ UAC-09] New blocktype `HttpExtractor` is implemented in std-extension. via #134 
- [x] [UAC-10] New blocktype `ArchiveInterpreter` is implemented in std-extension. via #135
- [x] [UAC-11] New blocktype `FilePicker` is implemented in std-extension. via #136 
- [x] [UAC-12] The current blocktype `CSVFileExtractor` is refactored to an `CSVInterpreter`. via #168 
- [x] [UAC-13] The former extractor-functionality of `CSVFileExtractor` is covered by the new `HTTPExtractor` and `ArchiveInterpreter`. via #169
- [x] [UAC-14] The example.jv-files are adapted to using the new blocks `HTTPExtractor` and `ArchiveInterpreter`. via #169 and TODO
- [x] [UAC-15] All conditional columns of an GTFS-Layout are considered as required --> out of scope, via #85
- [x] [UAC-16] The current block `SQLiteSink` accepts multiple inputs. --> for a PoC, multiple sinks are used, rather than multiple inputs for one sink, this works out of the box
- [x] ~~[UAC-17] The current block `SQLiteSink` process the new tables' name. obsolet via #164~~
- [x] [UAC-18] The current block `SQLiteSink` does not recreate an DB each call. --> already implemented, if an database exists, the db gets opened, otherwise created.
- [x] [UAC-19] Parallel processing of independ blocks does not interfer the overall execution .--> already implemented
- [x] [UAC-20] Jayvee processes successfully [`0002-mobility.jv`](https://github.com/jvalue/jayvee/blob/main/rfc/0002-mobility.jv) via #180 

## Examples
A detailled explanation of all UACs and further context is provided by the [RFC0002](https://github.com/jvalue/jayvee/tree/main/rfc/0002-mobility-extension)

## Definitions of Done
- [x] All PRs has been opened and accepted
- [x] All user acceptance criteria are met
- [x] All tests are passing
