### ISSUE TITLE
[FEATURE] Smoke Tests for Examples

### ISSUE THREAD

**Issue by georg-schwarz** [jvalue/jayvee#245]
## User Story
1. As a {Jayvee developer}
2. I want {have smoke tests using the example files}
3. So that {I can be sure that my changes don't break the examples}

## User Acceptance Criteria
- [x] There is a documented test setup for smoke tests (#414)
- [x] There is a script to execute the smoke tests (#389)
- [x] The smoke tests should execute the jayvee files in the `examples` directory and fail if one of the executions fails (#389)
- [x] The smoke tests are checked via GitHub Actions (#389)

## Notes
These smoke tests are rather high-level. We will need to complement them with lower level tests in the future (e.g. unit tests for the interpreter blocks).

## Definitions of Done
- [x] A PR has been opened and accepted
- [x] All user acceptance criteria are met
- [x] All tests are passing

**Comment by georg-schwarz** [comment]
Should be implemented, right @f3l1x98 ?
